language: cpp

env:
    global:
        - LINUX_DIST=trusty
        - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
        - RUN_TESTS=true
        - COVERAGE=false

matrix:
    include:
        - os: linux
          dist: trusty
          env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
          addons:
            apt:
                packages:
                    - g++-5
        
before_install:
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS"
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}"

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v

    # Download CMake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script:
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .. 
     - make
     - ctest

